동일한 port size에 대한 분석

어떠한 규격이 존재하는건가?

In [1]:
import warnings
warnings.filterwarnings(action="ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
train_df = pd.read_parquet("../../data/HD_data/train_v2_remove.parquet")
test_df = pd.read_parquet("../../data/HD_data/test_v2_remove.parquet")

In [4]:
train_df.dtypes

AIR_TEMPERATURE              float64
ARI_CO_BR                      uint8
ARI_CO_CA                      uint8
ARI_CO_CL                      uint8
ARI_CO_CN                      uint8
                              ...   
SHIP_TYPE_CATEGORY_Tanker      uint8
U_WIND                       float64
V_WIND                       float64
month                          int64
year                           int64
Length: 274, dtype: object

In [4]:
train_df["PORT_SIZE"].unique()

array([2.615416e-03, 2.166170e-04, 1.614168e-03, 3.561180e-04,
       1.032750e-04, 4.110000e-05, 9.896490e-04, 2.560450e-04,
       1.742858e-03, 5.198700e-04, 4.554380e-04, 1.304860e-04,
       5.946910e-04, 1.103840e-04, 4.450000e-05, 2.630000e-05,
       2.642870e-04, 1.025630e-03, 3.986360e-04, 1.488110e-04,
       3.604280e-04, 4.271150e-04, 1.249260e-04, 4.788750e-04,
       8.300000e-05, 4.990000e-05, 3.650000e-05, 1.660242e-03,
       1.131810e-04, 5.150000e-05, 3.319900e-04, 5.750000e-05,
       1.166720e-04, 6.140000e-05, 5.440000e-05, 3.200800e-04,
       4.498540e-04, 5.565580e-04, 4.260000e-05, 1.640000e-05,
       6.250000e-05, 1.450590e-04, 9.391550e-04, 1.027827e-03,
       1.032300e-04, 6.600000e-05, 5.517320e-04, 8.000000e-05,
       1.074280e-04, 2.440500e-04, 1.768880e-04, 2.347970e-04,
       1.550470e-04, 6.430000e-05, 1.818660e-04, 5.760000e-05,
       1.279490e-04, 6.920000e-05, 4.080000e-05, 1.069270e-04,
       1.240800e-04, 1.965770e-04, 5.670000e-05, 6.1753

In [5]:
test_df["PORT_SIZE"].unique()

array([2.615416e-03, 1.027827e-03, 1.742858e-03, 1.818660e-04,
       5.517320e-04, 8.000000e-05, 2.166170e-04, 5.750000e-05,
       1.032750e-04, 6.175320e-04, 1.550000e-05, 3.986360e-04,
       1.025630e-03, 3.940000e-05, 9.896490e-04, 1.768880e-04,
       1.614168e-03, 7.010000e-05, 5.565580e-04, 4.271150e-04,
       9.391550e-04, 1.660242e-03, 6.140000e-05, 4.554380e-04,
       1.488110e-04, 2.347970e-04, 3.604280e-04, 6.920000e-05,
       4.770000e-05, 1.103840e-04, 1.131810e-04, 5.946910e-04,
       1.965770e-04, 1.032300e-04, 1.060000e-05, 1.317080e-04,
       1.550470e-04, 5.550000e-06, 4.788750e-04, 1.074280e-04,
       2.642870e-04, 3.200800e-04, 3.319900e-04, 5.150000e-05,
       1.279490e-04, 5.198700e-04, 1.304860e-04, 6.850000e-05,
       2.630000e-05, 3.561180e-04, 2.440500e-04, 1.240800e-04,
       5.440000e-05, 9.750000e-06, 5.670000e-05, 4.080000e-05,
       1.421460e-04, 2.560450e-04, 5.760000e-05, 1.166720e-04,
       1.450590e-04, 6.600000e-05, 1.069270e-04, 8.9600

In [6]:
assert sorted(train_df["PORT_SIZE"].unique()) == sorted(test_df["PORT_SIZE"].unique())

In [9]:
le = LabelEncoder() # 자동으로 오름차순 정렬해서 1부터 labeling함
le.fit(train_df["PORT_SIZE"])

LabelEncoder()

In [10]:
le.classes_

array([4.500000e-06, 4.580000e-06, 5.550000e-06, 5.710000e-06,
       6.040000e-06, 6.450000e-06, 8.110000e-06, 8.290000e-06,
       9.750000e-06, 1.060000e-05, 1.130000e-05, 1.190000e-05,
       1.200000e-05, 1.550000e-05, 1.640000e-05, 1.740000e-05,
       2.540000e-05, 2.570000e-05, 2.580000e-05, 2.630000e-05,
       2.910000e-05, 3.050000e-05, 3.230000e-05, 3.650000e-05,
       3.660000e-05, 3.870000e-05, 3.940000e-05, 4.080000e-05,
       4.110000e-05, 4.210000e-05, 4.260000e-05, 4.410000e-05,
       4.450000e-05, 4.770000e-05, 4.990000e-05, 5.150000e-05,
       5.440000e-05, 5.670000e-05, 5.750000e-05, 5.760000e-05,
       5.960000e-05, 6.140000e-05, 6.250000e-05, 6.430000e-05,
       6.600000e-05, 6.850000e-05, 6.920000e-05, 7.010000e-05,
       7.440000e-05, 8.000000e-05, 8.300000e-05, 8.960000e-05,
       1.032300e-04, 1.032750e-04, 1.069270e-04, 1.074280e-04,
       1.103840e-04, 1.131810e-04, 1.166720e-04, 1.240800e-04,
       1.249260e-04, 1.279490e-04, 1.304860e-04, 1.3170

In [15]:
le.inverse_transform([1])

array([4.58e-06])